---
- name: pause module demo
  hosts: localhost
  gather_facts: no
  vars:
    wait_time: 10
  tasks:
    - name: pause for {{ wait_time | int }} second(s)
      ansible.builtin.pause:
        seconds: "{{ wait_time | int }}"
        prompt: "Press enter to continue"

    - name: message
      ansible.builtin.debug:
        msg: "The wait is over"
