---
- name: debug module demo
  hosts: localhost
  gather_facts: no
  tasks:
    - name: say hello
      ansible.builtin.debug:
    - name: say something
      ansible.builtin.debug:
        msg: "something"
